//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rezume.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artefact_rezume
    {
        public int Id_artefact_rezume { get; set; }
        public int Id_tip { get; set; }
        public int Id_rezume { get; set; }
        public byte[] Fail { get; set; }
    
        public virtual RezumeV RezumeV { get; set; }
        public virtual Tip_artefact Tip_artefact { get; set; }
    }
}
