//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rezume.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RezumeEntities3 : DbContext
    {
        public RezumeEntities3()
            : base("name=RezumeEntities3")
        {
        }
        private static RezumeEntities3 _context;
        

        public static RezumeEntities3 GetContext()
        {
            if (_context == null)
                _context = new RezumeEntities3();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artefact_rezume> Artefact_rezume { get; set; }
        public virtual DbSet<HR> HR { get; set; }
        public virtual DbSet<Kandidat> Kandidat { get; set; }
        public virtual DbSet<Obrazovanie> Obrazovanie { get; set; }
        public virtual DbSet<RezumeV> RezumeV { get; set; }
        public virtual DbSet<Status_rezume> Status_rezume { get; set; }
        public virtual DbSet<Status_vakanciy> Status_vakanciy { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tip_artefact> Tip_artefact { get; set; }
        public virtual DbSet<Uroven_obr> Uroven_obr { get; set; }
        public virtual DbSet<Vakanciy> Vakanciy { get; set; }
    }
}
