//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rezume.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obrazovanie
    {
        public int Id_obrazovanie { get; set; }
        public int Id_kandidat { get; set; }
        public int Id_uroven_obr { get; set; }
        public string Specialnost { get; set; }
        public int God_ocon { get; set; }
        public string Name_uch { get; set; }
        public string Num_doc { get; set; }
    
        public virtual Kandidat Kandidat { get; set; }
        public virtual Uroven_obr Uroven_obr { get; set; }
    }
}
