//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rezume.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RezumeV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RezumeV()
        {
            this.Artefact_rezume = new HashSet<Artefact_rezume>();
        }
    
        public int Id_rezume { get; set; }
        public int Id_kandidat { get; set; }
        public int Id_vakanciy { get; set; }
        public Nullable<int> Opyt_rabot { get; set; }
        public Nullable<decimal> Ogidaemay_ZP { get; set; }
        public string Opisanie_navukov { get; set; }
        public System.DateTime Date_sozdaniy { get; set; }
        public int Id_status { get; set; }
        public Nullable<int> Id_HR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Artefact_rezume> Artefact_rezume { get; set; }
        public virtual HR HR { get; set; }
        public virtual Kandidat Kandidat { get; set; }
        public virtual Status_rezume Status_rezume { get; set; }
        public virtual Vakanciy Vakanciy { get; set; }
    }
}
