//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rezume.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vakanciy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vakanciy()
        {
            this.RezumeV = new HashSet<RezumeV>();
        }
    
        public int Id_vakanciy { get; set; }
        public string Name_vakanciy { get; set; }
        public System.DateTime Date_open { get; set; }
        public Nullable<decimal> ZP { get; set; }
        public Nullable<int> Neod_opyt_rabot { get; set; }
        public string Opisanie_neob_navukov { get; set; }
        public string Opisanie_obzn { get; set; }
        public int Id_status_vakanciy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RezumeV> RezumeV { get; set; }
        public virtual Status_vakanciy Status_vakanciy { get; set; }
    }
}
